/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/views/LandingPage.jsx",
  ],
  important: '.landing-page-scope',
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      "colors": {
        "surface-tint": "#5f5e61",
        "primary-fixed": "#e4e1e6",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "primary": "#000000",
        "primary-fixed-dim": "#c8c5ca",
        "on-surface-variant": "#47464b",
        "secondary-fixed-dim": "#d5c867",
        "on-secondary-container": "#6f650a",
        "outline": "#77767b",
        "inverse-surface": "#30312f",
        "on-secondary-fixed": "#201c00",
        "surface": "#fbf9f6",
        "on-tertiary-container": "#5f8a9e",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#a1cde3",
        "on-secondary-fixed-variant": "#4f4800",
        "on-primary-fixed": "#1b1b1e",
        "secondary-container": "#f2e580",
        "on-tertiary-fixed-variant": "#1e4c5f",
        "inverse-primary": "#c8c5ca",
        "on-surface": "#1b1c1a",
        "tertiary-fixed": "#bee9ff",
        "surface-bright": "#fbf9f6",
        "on-error-container": "#93000a",
        "surface-variant": "#e4e2df",
        "surface-container-low": "#f5f3f0",
        "secondary": "#695f02",
        "on-primary-container": "#858387",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "background": "#fbf9f6",
        "secondary-fixed": "#f2e580",
        "on-primary": "#ffffff",
        "surface-dim": "#dbdad7",
        "inverse-on-surface": "#f2f0ed",
        "surface-container": "#efeeeb",
        "on-tertiary-fixed": "#001f2a",
        "on-background": "#1b1c1a",
        "tertiary-container": "#001f2a",
        "surface-container-highest": "#e4e2df",
        "on-error": "#ffffff",
        "tertiary": "#000000",
        "outline-variant": "#c8c5cb",
        "primary-container": "#1b1b1e",
        "on-primary-fixed-variant": "#47464a",
        "surface-container-high": "#eae8e5"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin-desktop": "2.5rem",
        "gutter": "1rem",
        "space-xs": "0.25rem",
        "space-2xl": "3.5rem",
        "space-md": "1rem",
        "space-xl": "2.25rem",
        "gutter-tablet": "1.25rem",
        "margin-tablet": "1.5rem",
        "gutter-desktop": "1.5rem",
        "space-sm": "0.5rem",
        "space-lg": "1.5rem",
        "margin": "1rem"
      },
      "fontFamily": {
        "label-md": ["Space Mono", "monospace"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "code-sm": ["Space Mono", "monospace"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-xl-mobile": ["Space Grotesk", "sans-serif"],
        "code-md": ["Space Mono", "monospace"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "label-sm": ["Space Mono", "monospace"],
        "label-lg": ["Space Mono", "monospace"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "body-md": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        "body-sm": ["Space Grotesk", "sans-serif"]
      },
      "fontSize": {
        "label-md": ["11px", { "lineHeight": "14px", "letterSpacing": "0.06em", "fontWeight": "700" }],
        "headline-md": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "code-sm": ["11px", { "lineHeight": "16px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-xl-mobile": ["32px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "code-md": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "600" }],
        "label-sm": ["10px", { "lineHeight": "12px", "letterSpacing": "0.08em", "fontWeight": "700" }],
        "label-lg": ["13px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "700" }],
        "headline-xl": ["48px", { "lineHeight": "54px", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "30px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-sm": ["12px", { "lineHeight": "18px", "fontWeight": "400" }]
      }
    },
  },
}
