export class PlaybackEngine {
  constructor() {
    this.snapshots = [];
    this.currentIndex = 0;
    this.speed = 1; // 1x speed default
    this.baseDelay = 300; // ms per step at 1x
    this.isPlaying = false;
    this.intervalId = null;
    this.subscribers = new Set();
  }

  // Load a new array of snapshots generated by an algorithm
  loadSnapshots(snapshots) {
    this.pause();
    this.snapshots = snapshots;
    this.currentIndex = 0;
    this.notify();
  }

  play() {
    if (this.isPlaying || this.currentIndex >= this.snapshots.length - 1) return;
    this.isPlaying = true;
    this.notify();
    this.scheduleNextStep();
  }

  pause() {
    if (!this.isPlaying) return;
    this.isPlaying = false;
    if (this.intervalId) {
      clearTimeout(this.intervalId);
      this.intervalId = null;
    }
    this.notify();
  }

  scheduleNextStep() {
    if (!this.isPlaying) return;
    
    this.intervalId = setTimeout(() => {
      if (this.currentIndex < this.snapshots.length - 1) {
        this.currentIndex++;
        this.notify();
        this.scheduleNextStep();
      } else {
        this.pause();
      }
    }, this.baseDelay / this.speed);
  }

  stepForward() {
    this.pause();
    if (this.currentIndex < this.snapshots.length - 1) {
      this.currentIndex++;
      this.notify();
    }
  }

  stepBack() {
    this.pause();
    if (this.currentIndex > 0) {
      this.currentIndex--;
      this.notify();
    }
  }

  setSpeed(speedMultiplier) {
    this.speed = speedMultiplier;
    this.notify();
  }

  seek(index) {
    this.pause();
    if (index >= 0 && index < this.snapshots.length) {
      this.currentIndex = index;
      this.notify();
    }
  }

  reset() {
    this.pause();
    this.currentIndex = 0;
    this.notify();
  }

  // State access for UI
  getCurrentState() {
    return {
      snapshots: this.snapshots,
      snapshot: this.snapshots[this.currentIndex] || null,
      currentIndex: this.currentIndex,
      totalSteps: this.snapshots.length,
      isPlaying: this.isPlaying,
      speed: this.speed,
      isFinished: this.snapshots.length > 0 && this.currentIndex === this.snapshots.length - 1
    };
  }

  // Subscription system for React hooks
  subscribe(callback) {
    this.subscribers.add(callback);
    return () => this.subscribers.delete(callback);
  }

  notify() {
    const state = this.getCurrentState();
    this.subscribers.forEach(callback => callback(state));
  }
}
